package web

// TemplateData holds data to be passed to templates
type IndexTemplateData struct {
	UIText_UpdateAvailable         string
	UIText_UpdateLater             string
	UIText_UpdateNow               string
	UIText_UpdateInstalling        string
	UIText_UpdateFailed            string
	UIText_UpdateDescription       string
	UIText_MajorUpdateTitle        string
	UIText_MajorUpdateWarning      string
	UIText_MajorUpdateConfirm      string
	UIText_UpdateReleaseNotes      string
	UIText_UpdateRetry             string
	Version                        string
	Branch                         string
	SSUIIdentifier                 string
	UIText_StartButton             string
	UIText_StopButton              string
	UIText_Settings                string
	UIText_Update_SteamCMD         string
	UIText_Console                 string
	UIText_Detection_Events        string
	UIText_Backend_Log             string
	UIText_Backup_Manager          string
	UIText_Connected_PlayersHeader string
	UIText_GameServer              string
	UIText_Uptime                  string
	UIText_PlayersOnline           string
	UIText_LatestBackup            string
	UIText_ServerOutput            string
	UIText_ServerActivity          string
	UIText_StreamConnected         string
	UIText_StreamConnecting        string
	UIText_StreamReconnecting      string
	UIText_StreamPaused            string
	UIText_Pause                   string
	UIText_Resume                  string
	UIText_Clear                   string
	UIText_NoPlayers               string
	UIText_PlayersUnavailable      string
	UIText_RecentBackups           string
	UIText_BackupHistory           string
	UIText_ViewAllBackups          string
	UIText_ShowRecentBackups       string
	UIText_Refresh                 string
	UIText_Close                   string
	UIText_StateUncertain          string
	UIText_StateStopped            string
	UIText_StateStarting           string
	UIText_StateLoadingMap         string
	UIText_StateHostingSession     string
	UIText_StateRunning            string
	UIText_StateStopping           string
	UIText_Discord_Info            string
	UIText_API_Info                string
	UIText_Copyright1              string
	UIText_Copyright2              string
}

// ConfigTemplateData holds data for the config page template
type ConfigTemplateData struct {
	// Config values
	DiscordToken                            string
	ControlChannelID                        string
	EventLogChannelID                       string
	StatusPanelChannelID                    string
	LogChannelID                            string
	ControlPanelChannelID                   string
	BlackListFilePath                       string
	IsDiscordEnabled                        string
	IsDiscordEnabledTrueSelected            string
	IsDiscordEnabledFalseSelected           string
	RotateServerPassword                    string
	RotateServerPasswordTrueSelected        string
	RotateServerPasswordFalseSelected       string
	GameBranch                              string
	Difficulty                              string
	StartCondition                          string
	StartLocation                           string
	ServerName                              string
	SaveName                                string
	WorldID                                 string
	ServerMaxPlayers                        string
	ServerPassword                          string
	ServerAuthSecret                        string
	AdminPassword                           string
	GamePort                                string
	UpdatePort                              string
	UPNPEnabled                             string
	UPNPEnabledTrueSelected                 string
	UPNPEnabledFalseSelected                string
	AutoSave                                string
	AutoSaveTrueSelected                    string
	AutoSaveFalseSelected                   string
	SaveInterval                            string
	AutoPauseServer                         string
	AutoPauseServerTrueSelected             string
	AutoPauseServerFalseSelected            string
	LocalIpAddress                          string
	StartLocalHost                          string
	StartLocalHostTrueSelected              string
	StartLocalHostFalseSelected             string
	ServerVisible                           string
	ServerVisibleTrueSelected               string
	ServerVisibleFalseSelected              string
	UseSteamP2P                             string
	UseSteamP2PTrueSelected                 string
	UseSteamP2PFalseSelected                string
	ExePath                                 string
	AdditionalParams                        string
	AutoRestartServerTimer                  string
	AutoRestartCountdown                    string
	IsNewTerrainAndSaveSystem               string
	IsNewTerrainAndSaveSystemTrueSelected   string
	IsNewTerrainAndSaveSystemFalseSelected  string
	AutoStartServerOnStartup                string
	AutoStartServerOnStartupTrueSelected    string
	AutoStartServerOnStartupFalseSelected   string
	AllowAutoGameServerUpdates              string
	AllowAutoGameServerUpdatesTrueSelected  string
	AllowAutoGameServerUpdatesFalseSelected string
	CreateSSUILogFile                       string
	CreateSSUILogFileTrueSelected           string
	CreateSSUILogFileFalseSelected          string
	CreateGameServerLogFile                 string
	CreateGameServerLogFileTrueSelected     string
	CreateGameServerLogFileFalseSelected    string

	UIText_ConfigHeadline       string
	UIText_ServerConfig         string
	UIText_BackToDashboard      string
	UIText_DiscordIntegration   string
	UIText_SLPModIntegration    string
	UIText_DetectionManager     string
	UIText_ConfigurationWizard  string
	UIText_PleaseSelectSection  string
	UIText_UseWizardAlternative string
	UIText_BasicSettings        string
	UIText_NetworkSettings      string
	UIText_AdvancedSettings     string
	UIText_TerrainSettings      string
	UIText_BasicServerSettings  string

	UIText_ServerName                     string
	UIText_ServerNameInfo                 string
	UIText_SaveName                       string
	UIText_SaveNameInfo                   string
	UIText_WorldID                        string
	UIText_WorldIDInfo                    string
	UIText_MaxPlayers                     string
	UIText_MaxPlayersInfo                 string
	UIText_ServerPassword                 string
	UIText_ServerPasswordInfo             string
	UIText_AdminPassword                  string
	UIText_AdminPasswordInfo              string
	UIText_AutoSave                       string
	UIText_AutoSaveInfo                   string
	UIText_SaveInterval                   string
	UIText_SaveIntervalInfo               string
	UIText_AutoPauseServer                string
	UIText_AutoPauseServerInfo            string
	UIText_NetworkConfiguration           string
	UIText_GamePort                       string
	UIText_GamePortInfo                   string
	UIText_UpdatePort                     string
	UIText_UpdatePortInfo                 string
	UIText_UPNPEnabled                    string
	UIText_UPNPEnabledInfo                string
	UIText_LocalIpAddress                 string
	UIText_LocalIpAddressInfo             string
	UIText_StartLocalHost                 string
	UIText_StartLocalHostInfo             string
	UIText_ServerVisible                  string
	UIText_ServerVisibleInfo              string
	UIText_UseSteamP2P                    string
	UIText_UseSteamP2PInfo                string
	UIText_AdvertiserTitle                string
	UIText_AdvertiserSummary              string
	UIText_AdvertiserConfigure            string
	UIText_AdvertiserExplanation          string
	UIText_AdvertiserMasterServer         string
	UIText_AdvertiserDisabled             string
	UIText_AdvertiserAuto                 string
	UIText_AdvertiserIPv4                 string
	UIText_AdvertiserDNS                  string
	UIText_AdvertiserAddress              string
	UIText_AdvertiserRestartWarning       string
	UIText_AdvertiserSaveRestart          string
	UIText_AdvertiserRestarting           string
	UIText_Cancel                         string
	UIText_Close                          string
	UIText_AdvancedConfiguration          string
	UIText_TLSCertificateTitle            string
	UIText_TLSCertificateSummary          string
	UIText_TLSConfigure                   string
	UIText_TLSCertificateExplanation      string
	UIText_TLSCertificateFormats          string
	UIText_TLSCertificateFile             string
	UIText_TLSPrivateKeyFile              string
	UIText_TLSRestartRequired             string
	UIText_TLSRestartWarning              string
	UIText_TLSSaveRestart                 string
	UIText_TLSRestarting                  string
	UIText_ServerAuthSecret               string
	UIText_ServerAuthSecretInfo           string
	UIText_ServerExePath                  string
	UIText_ServerExePathInfo              string
	UIText_ServerExePathInfo2             string
	UIText_AdditionalParams               string
	UIText_AdditionalParamsInfo           string
	UIText_ShowExpertSettings             string
	UIText_ShowExpertSettingsInfo         string
	UIText_AutoRestartServerTimer         string
	UIText_AutoRestartServerTimerInfo     string
	UIText_AutoRestartCountdown           string
	UIText_AutoRestartCountdownInfo       string
	UIText_GameBranch                     string
	UIText_GameBranchInfo                 string
	UIText_TerrainSettingsHeader          string
	UIText_TerrainWarning                 string
	UIText_UseNewTerrainAndSave           string
	UIText_UseNewTerrainAndSaveInfo       string
	UIText_Difficulty                     string
	UIText_DifficultyInfo                 string
	UIText_StartCondition                 string
	UIText_StartConditionInfo             string
	UIText_StartLocation                  string
	UIText_StartLocationInfo              string
	UIText_TerrainSettingsFillHint        string
	UIText_AutoStartServerOnStartup       string
	UIText_AutoStartServerOnStartupInfo   string
	UIText_AllowAutoGameServerUpdates     string
	UIText_AllowAutoGameServerUpdatesInfo string
	UIText_CreateSSUILogFile              string
	UIText_CreateSSUILogFileInfo          string
	UIText_CreateGameServerLogFile        string
	UIText_CreateGameServerLogFileInfo    string

	UIText_DiscordIntegrationTitle    string
	UIText_DiscordBotToken            string
	UIText_DiscordBotTokenInfo        string
	UIText_ChannelConfiguration       string
	UIText_AdminCommandChannel        string
	UIText_AdminCommandChannelInfo    string
	UIText_ControlPanelChannel        string
	UIText_ControlPanelChannelInfo    string
	UIText_RotateServerPassword       string
	UIText_RotateServerPasswordInfo   string
	UIText_EventLogChannel            string
	UIText_EventLogChannelInfo        string
	UIText_StatusPanelChannel         string
	UIText_StatusPanelChannelInfo     string
	UIText_LogChannel                 string
	UIText_LogChannelInfo             string
	UIText_BannedPlayersListPath      string
	UIText_BannedPlayersListPathInfo  string
	UIText_DiscordIntegrationBenefits string
	UIText_DiscordBenefit1            string
	UIText_DiscordBenefit2            string
	UIText_DiscordBenefit3            string
	UIText_DiscordBenefit4            string
	UIText_DiscordBenefit5            string
	UIText_DiscordSetupInstructions   string

	UIText_Copyright        string
	UIText_CopyrightConfig1 string
	UIText_CopyrightConfig2 string

	UIText_SLP_Title                  string
	UIText_SLP_Description            string
	UIText_SLP_ReadyToInstall         string
	UIText_SLP_InstallButton          string
	UIText_SLP_UploadModPackage       string
	UIText_SLP_UploadDescription      string
	UIText_SLP_UploadDescriptionLink  string
	UIText_SLP_InstallFirst           string
	UIText_SLP_InstallFirstSubtext    string
	UIText_SLP_DragDropHere           string
	UIText_SLP_OrClickToSelect        string
	UIText_SLP_UploadButton           string
	UIText_SLP_ManageInstallation     string
	UIText_SLP_UninstallWarning       string
	UIText_SLP_UninstallButton        string
	UIText_SLP_UpdateWorkshopMods     string
	UIText_SLP_UpdateWorkshopModsDesc string
	UIText_SLP_UpdateButton           string
	UIText_SLP_InstalledMods          string

	IsStationeersLaunchPadEnabled string

	// Expert Settings
	ShowExpertSettings              string
	ShowExpertSettingsTrueSelected  string
	ShowExpertSettingsFalseSelected string

	// Expert Settings values
	Debug                                                 string
	DebugTrueSelected                                     string
	DebugFalseSelected                                    string
	LogLevel                                              string
	LogClutterToConsole                                   string
	LogClutterToConsoleTrueSelected                       string
	LogClutterToConsoleFalseSelected                      string
	IsSSCMEnabled                                         string
	IsSSCMEnabledTrueSelected                             string
	IsSSCMEnabledFalseSelected                            string
	IsConsoleEnabled                                      string
	IsConsoleEnabledTrueSelected                          string
	IsConsoleEnabledFalseSelected                         string
	SSUIWebPort                                           string
	IsUpdateEnabled                                       string
	IsUpdateEnabledTrueSelected                           string
	IsUpdateEnabledFalseSelected                          string
	AllowPrereleaseUpdates                                string
	AllowPrereleaseUpdatesTrueSelected                    string
	AllowPrereleaseUpdatesFalseSelected                   string
	AllowMajorUpdates                                     string
	AllowMajorUpdatesTrueSelected                         string
	AllowMajorUpdatesFalseSelected                        string
	AuthEnabled                                           string
	AuthEnabledTrueSelected                               string
	AuthEnabledFalseSelected                              string
	AuthTokenLifetime                                     string
	DiscordCharBufferSize                                 string
	BackupKeepLastN                                       string
	IsCleanupEnabled                                      string
	IsCleanupEnabledTrueSelected                          string
	IsCleanupEnabledFalseSelected                         string
	BackupKeepDailyFor                                    string
	BackupKeepWeeklyFor                                   string
	BackupKeepMonthlyFor                                  string
	BackupCleanupInterval                                 string
	BackupWaitTime                                        string
	AdvertiserOverride                                    string
	IsStationeersLaunchPadAutoUpdatesEnabled              string
	IsStationeersLaunchPadAutoUpdatesEnabledTrueSelected  string
	IsStationeersLaunchPadAutoUpdatesEnabledFalseSelected string
}
